# Write a a program to input eight n_1 from the user and display all the unique n_1 (once)
s = set()
n_1 = input("Enter  n_1 :")
s.add(n_1)
n_2 = input("Enter  n_2 :")
s.add(n_2)
n_3 = input("Enter  n_3 :")
s.add(n_3)
n_4 = input("Enter  n_4 :")
s.add(n_4)
n_5 = input("Enter  n_5 :")
s.add(n_5)
n_6 = input("Enter  n_6 :")
s.add(n_6)
n_7 = input("Enter  n_7 :")
s.add(n_7)
n_8 = input("Enter  n_8 :")
s.add(n_8)
print(s)