marks = []
student_marks_1 = int(input("Enter student marks :"))
marks.append(student_marks_1)
student_marks_2 = int(input("Enter student marks :"))
marks.append(student_marks_2)
student_marks_3 = int(input("Enter student marks :"))
marks.append(student_marks_3)
student_marks_4 = int(input("Enter student marks :"))
marks.append(student_marks_4)
student_marks_5 = int(input("Enter student marks :"))
marks.append(student_marks_5)
student_marks_6 = int(input("Enter student marks :"))
marks.append(student_marks_6)
print(marks)
marks.sort()
print(marks)